# Generated by Selenium IDE
from unicodedata import name
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

PATH = "/Users/marcovinciguerra/Github/Python/Selenium _Kahoot_bot/ChromeDriver/chromedriver"    
driver = webdriver.Chrome(PATH)

  
def test_a():
    driver.get("https://kahoot.it/")
    driver.set_window_size(1512, 945)
    driver.find_element(By.ID, "game-input").click()
    driver.find_element(By.ID, "game-input").send_keys("14988")
    driver.find_element(By.ID, "game-input").send_keys(Keys.ENTER)
    driver.find_element(By.XPATH, '//*[@id="nickname"]').click()
    driver.find_element(By.ID, "nickname").send_keys("vinci0000")
    driver.find_element(By.CSS_SELECTOR, ".sc-jJEJSO").click()
    element = driver.find_element(By.CSS_SELECTOR, ".sc-jJEJSO")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
  
if __name__ == "__main__":
    test_a()