# Generated by Selenium IDE
from unicodedata import name
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

PATH = "/Users/marcovinciguerra/Github/Python/Selenium _Kahoot_bot/ChromeDriver/chromedriver"    
driver = webdriver.Chrome(PATH)

  
def test_a():
    driver.get("https://kahoot.it/")
    driver.set_window_size(1512, 945)
    driver.find_element(By.ID, "game-input").click()
    driver.find_element(By.ID, "game-input").send_keys("646816")
    driver.find_element(By.ID, "game-input").send_keys(Keys.ENTER)
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//input[@id='nickname']"))).send_keys("vinci0000")
    driver.find_element(By.ID, "nickname").click()
    driver.find_element(By.ID, "nickname").send_keys("vinci000")
    driver.find_element(By.CSS_SELECTOR, ".sc-jJEJSO").click()
    element = driver.find_element(By.CSS_SELECTOR, ".sc-jJEJSO")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
  
if __name__ == "__main__":
    test_a()